### ISSUE TITLE
consider renaming github repo

### ISSUE THREAD

**Issue by danmarsden** [kuracloud/moodle-block_kuracloud#3]
Hi there, 
I have just started looking at this plugin for approval in the moodle.org plugins db - it's looking pretty good so far, nice work!

You may want to rename the repository here from "moodle-integration" to something that fits the "frankenstyle" naming convention that is familiar to moodle site admins using github - this would be:
"moodle-block_kuracloud" - most moodle plugins hosted on github use this naming convention.

This is completely optional and will not block approval in the plugins db, so feel free to close as "won't fix" for whatever reason! :-)

**Comment by shadowspawn** [comment]
Good tip, done, thanks.
