### ISSUE TITLE
Consider adding travis-ci integration.

### ISSUE THREAD

**Issue by danmarsden** [kuracloud/moodle-block_kuracloud#4]
The checks run in the moodle.org plugins db can also be run automatically here on github using the travis-ci integration.

More information on this is here:
https://moodle.org/mod/forum/discuss.php?d=323384
this will pick up a number of other things that we would normally notice in the review process.

Integrating with travis is optional and will not block approval in the plugins db, but it does make the review process a bit easier and usually provides a good way to ensure future compliance with coding guidelines etc.

**Comment by shadowspawn** [comment]
I have added .travis.yml and run the tests from a fork, but have some process to work through to add travis integration to kuracloud organisation, and not active in this fork yet.

**Comment by danmarsden** [comment]
great! - the github integration is really handy when you have pull requests and becomes even more powerful once you implement behat tests. One of my plugins picked up a regression caused in moodle upstream code last week
