### ISSUE TITLE
get_content called twice 

### ISSUE THREAD

**Issue by danmarsden** [kuracloud/moodle-block_kuracloud#5]
the function get_content() is called twice on each page when displaying a block... (historical reasons that I forget)

for this reason we usually add the following code to the top of the get_content function to avoid having the functions inside get_content from being called multiple times and impacting on performance.

        if ($this->content !== NULL) {
            return $this->content;
        }

let me know if you need more specific info.

**Comment by shadowspawn** [comment]
Good advice, thanks. 
Changed in 80487bb11ad2032aa05b25dcc880a70b3d907a5d

**Comment by danmarsden** [comment]
sweet - as soon as you're ready to upload a new version to the plugins db it will be ready for approval!
