### ISSUE TITLE
admin settings should probably be wrapped by ADMIN->fulltree check

### ISSUE THREAD

**Issue by danmarsden** [kuracloud/moodle-block_kuracloud#6]
https://github.com/kuracloud/moodle-integration/blob/master/settings.php#L28

the settings should probably be wrapped in:
```PHP
if ($ADMIN->fulltree) {
}
```

**Comment by shadowspawn** [comment]
I did experiment, but introduced UX breakages. Looking at an example in the docs, the calls being made to `admin_externalpage` and `$settings = null` are not protected by the `fulltree` check in the example:
https://docs.moodle.org/dev/Navigation_API#Add_Settings_folder_to_navigation

i.e. we are not making any calls to `admin_setting_*`

**Comment by danmarsden** [comment]
haha - yeah, my bad - I'm just used to doing those reviews a bit too quickly and didn't look close enough! - feel free to close this one off.

**Comment by shadowspawn** [comment]
Thanks Dan.
